apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shuttleday-staging

patches:
  - path: frontend-deployment.patch.yaml
  - path: api-deployment.patch.yaml
  - path: ingress.patch.yaml
resources:
- ../../base
