apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
  - cluster-issuer.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - ingress.yaml
  - service-account.yaml
  - service.yaml
  - statefulset.yaml
