apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: shuttleday
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: bTFrM2wmaW5kMG0xZQ==
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: shuttleday-api-secret
  namespace: shuttleday
stringData:
  MONGO_URL: "mongodb-0.mongo/?authSource=admin"
  MONGO_USER: "admin"
  MONGO_PW: "m1k3l&ind0m1e"
  SERVER_PORT: "2600"
  AWS_S3_SECRET_ACCESS_KEY: "iGtNo/YqYQ7GtNXiDW9Zvp4eI8Qk8b/8LUHgrxd2"
  AWS_S3_ACCESS_KEY_ID: "AKIA2MSHQPHJL55QB4FP"
  AWS_S3_BUCKET_NAME: "shuttleday-payments"
  G_AUTH_CLIENT_ID: "1068634634840-54f4f64s3pgj9vgqh26b4eseqdnvgp0v.apps.googleusercontent.com"
  ACCESS_TOKEN_SECRET: "836bc58751e704a555e037078d2bc060bd2c62299b953126"
  REFRESH_TOKEN_SECRET: "ad71a0aae23d2988ef974b3334f2638a2bb441c6299ecfa7"
---
kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: shuttleday-frontend-secret
  namespace: shuttleday
stringData:
  REACT_APP_CLIENT_ID: 1068634634840-54f4f64s3pgj9vgqh26b4eseqdnvgp0v.apps.googleusercontent.com
  REACT_APP_API_LINK: https://api.shuttleday.info
